name: Deploy via Docker Compose

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Construir y reiniciar con Docker Compose
        run: |
          docker compose down
          docker compose up -d --build
          docker system prune -f
